### ISSUE TITLE
Lightbox Plugin hinzufügen

### ISSUE THREAD

**Issue by michiwieland** [altcomphsr/altcomphsr.vshsr.ch#12]
Was meint ihr zu einem Lightbox Plugin, damit wir die Anleitungsbilder in vergrösserter Form anzeigen können?

Mein Vorschlag: [jekyll-lightbox](https://github.com/appfoundry/jekyll-lightbox)

**Comment by michiwieland** [comment]
Das dynamische Laden von Content einer anderen Seite scheint sich nicht sehr gut mit dem Plugin zu vertragen. Evtl ist es aber auch ein generelles Problem, dass der Inhalt der "reingeladenen" Seite nicht mehr speziell geparst wird.

**Comment by fabianhauser** [comment]
Das liegt daran, dass das Einbinden ein bisschen ein Hack ist, [siehe Code](https://github.com/altcomphsr/altcomphsr.vshsr.ch/blame/master/_hsr/email.md#L33). Der Ausschnitt wird bei der Ausgabe nicht mehr als Liquid geparsed, deshalb wird dieser Teil nicht sauber ausgegeben.

Das Einbinden der Konfiguration z.B. bei Thunderbird ist sowieso suboptimal, da somit Duplicated Content entsteht (SEO und so).

Von dem her müssten wir uns überlegen, ob wir das nicht irgendwie eleganter lösen können oder sonst ein eigenes Plugin schreiben...

Was denkt ihr?
