### ISSUE TITLE
"Sammelbecken" für weiteres

### ISSUE THREAD

**Issue by raphiz** [altcomphsr/altcomphsr.vshsr.ch#13]
Bin mir nicht sicher, ob das wirklich in den "Aufgabenbereich" vom Altcomp gehört - aber es wäre noch cool so ein Index mit anderen interessanten Dingen aus dem HSR-Universum zu sammeln, wie zum Beispiel:
- [ ] [HSR-Stud Zusammenfassungen](http://hsr-stud.github.io/)
- [ ] [Moodle "Autologin" skripte](https://gist.github.com/raphiz/96c2b07dacda746dd2f5)
- [ ] [Sync Skripte](https://gist.github.com/raphiz/29dd1ed3145b06b9398d) (Da wäre ein kleines dazu GUI auch ganz schick - falls jemand zu viel Zeit hat :laughing:)
- [ ] Empfehlung PDF Reader unter Linux (Bsp. [Master PDF Editor](https://code-industry.net/masterpdfeditor/) - non free aber funktioniert gut)
- [ ] [Github Education Pack](https://education.github.com/pack)
- [ ] Installation von [Intellij](https://www.jetbrains.com/student/) und Eclipse

Ist halt die Frage wo wir das unterkriegen und vorallem ist das teilweise eher "advanced" :wink:

**Comment by fabianhauser** [comment]
Hier auch noch Inputs aus dem #1 (_Kursive_ Bemerkungen von mir):
- Verknüpfen, unterstützen Community / Open-Source-Projekte an der HSR:
  - Python-Summit
  - _[Postgres Konferenz Schweiz](http://www.postgres-conference.ch/)_
  - HSR-Stud
    - **_Einstiegshilfe LaTeX?**_
  - [Studentenportal](https://github.com/studentenportal)
  - VSHSR  
    _Habe gehört, hier gäbe es in den nächsten Wochen eine neue Webseite?_
  - OSM, siehe auch http://geometalab.tumblr.com/
- Förderung Crypto (GPG etc.)?  
  _Dafür wäre vermutlich ein Grundsatzentscheid nötig, ob wir uns mit dem Thema befassen wollen oder nicht. Evtl. etwas heikel._

---

**Zum Moodle Autologin & Sync-Skripte**

Ich würde Vorschlagen, solche Projekte nicht direkt vom Verein aus zu machen, aber Ressourcen und Hilfestellungen zur Verfügung zu stellen (Repository in dieser Organisation, Erwähnung auf alt.comp.hsr-Webseite und evtl. Studienstart-Guide etc.).  Auch wenn natürlich die gleichen Personen beteiligt sein können! :)

Wir wären in dem Sinne eine Plattform für Projekte, welche für alle Studenten interessant sind.

Das Problem ist momentan ja nicht, dass es keine solchen Projekte gibt, aber es fehlt ein zentraler Ort, wo mitgearbeitet werden kann und übersichtlich darüber informiert wird. Das würde gemäss  [unserer Vereinsseite](http://altcomp.raphael.li/verein/) auch gut zu uns passen (womit der Kreisbeweis geschlossen wäre :blush:)

**Comment by raphiz** [comment]
Gute Ergänzungen, merci! 

Die Idee mit der Plattform ist super, aber so zentral muss es ja auch nicht sein. Ich finde es eigentlich super, dass das Studentenportal separat lebt. Es wäre mir wichtiger, dass wir auf eben solche Projekte hinweisen & verlinken.

Das gleiche gilt für die Skripte, die können gerne separat leben (einfach verlinken)

**Comment by fabianhauser** [comment]
Ich gebe dir absolut recht, dass grosse Projekte wie z.B. das Studentenportal besser in einem eigenen Projekt aufgehoben sind.

Bei den Skripten fände ich aber noch interessant, wenn wir eine Auswahl zur Verfügung stellen könnten. Für Windows und Mac gibt es ja den HSR-Mapper, für Linux fehlt etwas vergleichbares.

**Comment by murieletrentini** [comment]
Den HSR Mapper gibt es - ganz nach Philosophie der Schule - nur für Windows. ;-)
Für Mac fehlt eine entsprechende Alternative ebenfalls.

**Comment by fabianhauser** [comment]
Stimmt, den gibt es tatsächlich nur für Windows. Keine Ahnung wie ich auf die Idee gekommen bin :)

**Comment by fabianhauser** [comment]
Gerade eine Idee gehabt:

**Jährlicher Preis  bzw. Wettbewerb ausschreiben für coole Open Source Projekte.**
Preis: Bargeld, VSHSR Wurst&Drink Gutscheine, Technik?
Finanzierung: via Sponsoring? Es gibt ja einige Firmen, welche auch an Open Source interessiert sind. Wir können auch den VSHSR als Unterstützung anfragen.

Mir fallen da spontan folgende Kategorien ein:
- Open Source Projekte, welche das Studium an der HSR erleichtern (z.B. Share-Mount-Sync Programm oder so)
- Studien-, Bachelor & Masterarbeiten
- (Open Source Zusammenfassungen)

Das ganze soll zum Mitmachen motivieren und die "Awareness" steigern.

Was haltet ihr davon?

**Comment by raphiz** [comment]
An der GV haben wir dieses Ticket ausführlich besprochen.

Die folgenden Punkte werden in eine Tips und Tricks Seite (#22) verschoben:
- [ ] [HSR-Stud Zusammenfassungen](http://hsr-stud.github.io/)
- [ ] [Moodle "Autologin" skripte](https://gist.github.com/raphiz/96c2b07dacda746dd2f5)
- [ ] [Sync Skripte](https://gist.github.com/raphiz/29dd1ed3145b06b9398d) (Da wäre ein kleines dazu GUI auch ganz schick - falls jemand zu viel Zeit hat :laughing:)
- [ ] [Github Education Pack](https://education.github.com/pack)
- [ ] Installation von [Intellij](https://www.jetbrains.com/student/) und Eclipse
- Förderung Crypto (GPG etc.)
- Einstiegshilfe LaTeX

Alternative Software Empfehlungen werden direkt unter "Programme" geführt (Siehe #18)

Die Idee des Wettbewerbs habe ich in ein neues Ticket im Verein Repo verschoben (Siehe [Verein #8](https://github.com/altcomphsr/verein/issues/8))
