### ISSUE TITLE
Styleguide

### ISSUE THREAD

**Issue by michiwieland** [altcomphsr/altcomphsr.vshsr.ch#15]
Wollte gerade den Styleguide um den < kbd > Tag für Tastenkürzel erweitern. Ist der Styleguide bewusst im .gitignore? 
Ich denke man sollte den gesamten Styleguide, wie die restlichen Seiten auch, in das Template integrieren.(Header auslagern etc.)

Wollte den Styleguide um folgenden Punkt ergänzen:

<h3 id="kurzum">Tastenkürzel</h3>

Um ihre Arbeit speditiv zu erledigen, benutzt Maria gerne Tastenkürzel. Tastenkürzel werden immer wie folgt dargestellt.

<p><kbd>Alt</kbd> + <kbd>Comp</kbd> + <kbd>HSR</kbd></p>

**Comment by fabianhauser** [comment]
Also bei mir ist der Styleguide `pages/styleguide.md` nicht im `.gitignore` :smiley: 

> _site
> .sass-cache
> .jekyll-metadata
> .idea
