### ISSUE TITLE
Webseite online schalten

### ISSUE THREAD

**Issue by fabianhauser** [altcomphsr/altcomphsr.vshsr.ch#17]
Die Webseite ist jetzt auf dem "minimum" stand und könnte damit online gestellt werden.
- Deployment neu mit Travis CI (Doku [Deployment](https://docs.travis-ci.com/user/deployment/custom/), [Docker](https://docs.travis-ci.com/user/docker/))
- Die FTP-Logindaten sind im https://github.com/altcomphsr/pass abgelegt und momentan mit dem GPG-key von @raphiz, @michiwieland und @fabianhauser encrypted. Siehe https://www.passwordstore.org/

@raphiz : Willst du das anschauen oder soll ich? :)

**Comment by raphiz** [comment]
Wir sind nun live auf http://altcomphsr.vshsr.ch/ 🎉 
Die alte Development-Domain altcomp.raphael.li leitet nun auch korrekt auf http://altcomphsr.vshsr.ch/ weiter - ich werde die Subdomain in ein paar Wochen löschen

**Comment by fabianhauser** [comment]
Cool, vielen Dank für die tolle Arbeit @altcomphsr/vorstand ! :smiley:
