### ISSUE TITLE
Webseite TLS & Passwörter ändern

### ISSUE THREAD

**Issue by fabianhauser** [altcomphsr/altcomphsr.vshsr.ch#19]
- Es wäre cool, wenn die Webseite TLS hätte, mit Hospoint ist das ja Gratis.
- Die Passwörter für Hosting und Mail sollten mal angepasst werden.

Dafür müsste Kontakt mit dem/der Verantwortlichen vom VSHSR aufgenommen werden.

**Comment by raphiz** [comment]
Offenbar hanen wir nun TLS - die Seite ist ausschliesslich über https erreichbar!
@fabianhauser @michiwieland hat einer von euch das organisiert?

**Comment by fabianhauser** [comment]
Die Änderung des Passwortes wird gleich in altcomphsr/verein/issues/2 Rebranding angeschaut. Dieses Issue kann somit geschlossen werden.
