### ISSUE TITLE
Setup Jekyll für neue Webseite

### ISSUE THREAD

**Issue by fabianhauser** [altcomphsr/altcomphsr.vshsr.ch#2]
- Einfaches Jekyll Setup via https://github.com/altcomphsr/altcomphsr.vshsr.ch/ und test-subdomain
- Docker deployment?

**Comment by raphiz** [comment]
So, ich habe ganz unanständig ein basis Gerüst commited. Das sollte für den Anfang reichen - ich denke as default Theme ist im moment auch ganz ok.

Werde mich nun noch ums deployment kümmern...

**Comment by raphiz** [comment]
So, der master Branch wird nun automatisch auf https://altcomp.raphael.li/ deployed

**Comment by fabianhauser** [comment]
Cool, merci!
