### ISSUE TITLE
VPN unter Ubuntu 16.04 LTS - Pakete fehlen

### ISSUE THREAD

**Issue by nik-sta** [altcomphsr/altcomphsr.vshsr.ch#21]
Unter Ubuntu 16.04 LTS sind viele Pakete zum Theme VPN nicht standardmässig mitdabei, daher muss man diese selbständig nach-installieren. Sonst hat man die benötigten Einstellungen erst gar nicht zur Auswahl.

Link zu den benötigten Paketen: https://wiki.ubuntuusers.de/NetworkManager/VPN_Plugins/

**Comment by raphiz** [comment]
@nikolastankovic Danke für das Issue! Am besten wir schauen uns das (wie besprochen) zusammen an!

**Comment by raphiz** [comment]
Habe das soeben mal ausprobiert - neuerdings scheint man das Paket `network-manager-vpnc-gnome` und nicht mehr `network-manager-vpnc` zu installieren 😞 

...etwas komisch finde ich aber, dass es kein `network-manager-vpnc-kde` usw. gibt....naaja...
