### ISSUE TITLE
"Mitglied werden" Seite anpassen

### ISSUE THREAD

**Issue by raphiz** [altcomphsr/altcomphsr.vshsr.ch#23]
Da wir ja nun keinen Mitgliederbeitrag mehr haben wäre es cool, wenn man sich einfach auf der Seite mit der HSR E-Mail anmelden kann.

Zudem müssen wir potentiellen Mitgliedern schmackhaft machen, warum sich eine Mitgliedschaft lohnt:
- Updates über Open Source Veranstaltungen
- Mitarbeit & Engagement für eine offene HSR
- ...

**Comment by raphiz** [comment]
Wie wäre es damit?

---

Warum du Mitglied werden sollst?
- Du zeigst deine Unterstützung für Open Source & Freie Software
- Es gibt keinen Mitgliederbeitrag
- Engagiere dich für Freie Software und hilf mit, Open Source an der HSR zu fördern uns sichtbarer zu machen
- Du wirst von Zeit zu Zeit mit einem kurzen und prägnanten newsletter über aktuelle Veranstaltungen und Projekte Informiert

Es gibt zwar keinen Mitgliederbeitrag - trotzdem kannst du uns mit einem Gönnerbeitrag unterstützen!

Für was wir das Geld ausgeben, siehst du in unserem [Jahresbudget](https://github.com/openhsr/verein/blob/master/protokolle/2016/05_generalversammlung/protokoll.md#budget-2016)
und [Jahresabschluss](https://github.com/openhsr/verein/blob/master/protokolle/2016/05_generalversammlung/protokoll.md#jahresabschluss).

**Comment by fabianhauser** [comment]
Noch ein paar Ideen:
- Du wirst Teil der lebendigen Community um Open Source Projekte in Rapperswil
- Setze ein Zeichen für Freie Software
- Fördere unser Engagement für die Unterstützung von alternativen Betriebssystemen wie Linux und Mac OS X an der HSR
- Erhalte einen tollen open\HSR Sticker für dein Notebook!

**Comment by raphiz** [comment]
Wie wäre es damit?

## 

Warum du Mitglied werden sollst?
- Du wirst Teil der lebendigen Community um Open Source Projekte in Rapperswil
- Setze ein Zeichen für Freie Software
- Fördere unser Engagement für die Unterstützung von alternativen Betriebssystemen wie Linux und Mac OS X an der HSR
- Erhalte einen tollen open\HSR Sticker für dein Notebook!
- Du bekommst von Zeit zu Zeit mit einem kurz prägnanten Newsletter über aktuelle Veranstaltungen und Projekte

Es gibt keinen Mitgliederbeitrag - trotzdem kannst du uns mit einem Gönnerbeitrag unterstützen!

Für was wir das Geld ausgeben, siehst du in unserem [Jahresbudget](https://github.com/openhsr/verein/blob/master/protokolle/2016/05_generalversammlung/protokoll.md#budget-2016)
und [Jahresabschluss](https://github.com/openhsr/verein/blob/master/protokolle/2016/05_generalversammlung/protokoll.md#jahresabschluss).

**Comment by raphiz** [comment]
Evtl. muss noch etwas in zu Verpflichtungen erwähnt werden...und dass man auch ohne Github-Kenntnisse herzlich willkommen ist :)

**Comment by fabianhauser** [comment]
Siehe auch [Protokoll Vorstandssitzung 2016-07](https://github.com/openhsr/verein/pull/15).
