### ISSUE TITLE
Seite "Community" und "Verein" zusammenführen

### ISSUE THREAD

**Issue by raphiz** [altcomphsr/altcomphsr.vshsr.ch#25]
Ich würde gerne die beiden Unterseiten Community und Verein in eine vereinen...für mich ist diese Aufteilung etwas seltsam...ich kann mir gut vorstellen, dass diese Unterscheidung für "Neulinge" nicht ganz einfach zu verstehen ist.

Was meint Ihr?

**Comment by fabianhauser** [comment]
Die Idee hinter der Trennung war, "trockene" Informationen über den Verein und motivierende Formulierungen zu trennen :wink:

Aber der Verein ist so in der Tat nicht sehr prominent platziert. Magst du @raphiz das ganze zusammenführen?

**Comment by raphiz** [comment]
@fabianhauser ja, es machte ja auch Sinn so, aber da ja mit dem kostenlosen Mitgliederbeitrag Commutity ≈ Verein ist würde ich diese Trennung nicht so streng ziehen...
Jup, werde ich in Angriff nehmen - aber nicht mehr heute 😉
