### ISSUE TITLE
Grundlegende Struktur erstellen

### ISSUE THREAD

**Issue by fabianhauser** [altcomphsr/altcomphsr.vshsr.ch#3]
Bei den neuen statischen Seiten ist folgender Aufbau angedacht:
- Harte Fakten (URL, Einstellungen etc.)
- Einsteigeranleitung Ubuntu
- Anleitung MacOS?
## Grundlegende Seiten

Siehe #6 #7 #8
## Links
- [Alle Seiten im "alten" Wiki](http://altcomphsr.vshsr.ch/index.php?title=Spezial:Alle_Seiten)

**Comment by raphiz** [comment]
Ich würde vorschlagen, wir einigen uns auf eine einheitliche Grundstruktur. Mein Vorschlag wäre:
- Empfohlener Weg (Bsp. VPN mittels NetworkManager)
- Parameter (="Harte Fakten" / Gibt es bessere Begriffe?)
- Weitere Möglichkeiten (Bsp. via vpnc, AnyConnect usw)

Dabei würde ich sogar so weit gehen und unter "Weitere Möglichkeiten" nur verlinken - bzw. Software alternativen auflisten.

Was meint ihr?

**Comment by raphiz** [comment]
Hier ein konkretes Beispiel für VPN:

# Empfohlener Weg

Screenshots - step by step unter Ubuntu (latest)

## Hinweise zu anderen Distributionen

Paketname unter Arch: ...

Paketname unter Fedora: ...

# Parameter

| Parameter | Wert |
| --- | --- |
| Verbindungsname | `HSR VPN` (spielt keine Rolle) |
| Gruppenname | `vpn.hsr.ch` |
| Gruppenpasswort | `hsrremote` |
| Benutzerpasswort | dein HSR Passwort |
| Benutzername | dein HSR Benutzername |

# Weitere Möglichkeiten

Alternativ zum NetworkManager können Tools wie [VPNC](https://help.ubuntu.com/community/VPNClient#VPNC) verwendet werden.

**Comment by fabianhauser** [comment]
Denke wir sollten auf jeden Fall eine einheitlichen Seitenstruktur und Inhaltsaufbau haben;

### Seitenstruktur

Es gibt aus meiner Sicht folgende "Seitentypen": 

| Typ | Beispiel | URL |
| --- | --- | --- |
| Beschreiben einer Umgebung an der HSR | WLAN, Drucken | /hsr/SEITE |
| Konfiguration Bestimmter Programme | eclipse | /application/NAME |
| Allgemeine Seiten | Vereinsstatuten, Startseite | /SEITE |

### Inhaltsaufbau

Ich persönlich würde gerne die _Technischen Angaben_ /Parameter zu Oberst platzieren, denke, diese werden am häufigsten genutzt.

Zudem können wir ja die verschiedenen Distributionen / Unixe "gleichberechtigt" auflisten, Ubuntu aber immer als Erstes ;)? So hätten wir auch ein einheitliches System für Mac oder andere spezifische Einstellungen.

Jetzt bleibt noch die Frage, wie wir Studiengangspezifische Inhalte auflisten sollen. Mein Vorschlag wäre, dies auch direkt auf der entsprechenden Seite unter einer bestimmen Sektion aufzeichnen.

# Beispiel VPN

## Technische Angaben

| Parameter | Einstellung | Beschreibung |
| --- | --- | --- |
| param | value | Asdf |
| param2 | value2 | Querz |

## Systeme

### Ubuntu
1. Klick hier
2. Klick da
3. Tadaa

### Mac
1. Suppi
2. Soppi

## Studiengänge

### Informatik

Um auf Informatikressourcen zugreifen zu können, braucht es Parameter **A** bei **B**

## Links
- [Ubuntuusers anleitung](https://wiki.ubuntuusers.de/Blubber)

**Comment by raphiz** [comment]
Saubi, ich würde vorschlagen wir erstellen einen Styleguide...  :)
Ich hab mal damit begonnen

**Comment by fabianhauser** [comment]
@raphiz Habe den Styleguide mal noch komplett ausgeschrieben und versucht, alles so knapp wie möglich und nicht allzu trocken zu schreiben :smile:
So weit ich sehe sind jetzt die Punkte aus dem alten Wiki und unseren neuen Grundsätze ersichtlich.

Könntest du mal durchsehen, was ich vergessen habe oder noch zu verbessern wäre?

**Comment by raphiz** [comment]
@fabianhauser ich finde den Styleguide so sehr gelungen, ich denke damit können wir loslegen! Einzig die Anmerkung 

> Diese sollte Anfängergerecht sein (d.h. für Benutzer mit einem Fensterplatz).

Könnte evtl. etwas falsch verstanden werden :wink:  - schliesslich waren wir alle mal Anfänger - mit oder ohne Fensterplatz

**Comment by fabianhauser** [comment]
Stimmt, der Satz ist missverständlich, habe ihn umgeschrieben.
Die Erstellung der einzelnen Inhaltsseiten habe ich in einzelne Issues ausgelagert, somit kann dieses Issue geschlossen werden.
