### ISSUE TITLE
Font & Emoticons lokal einbinden

### ISSUE THREAD

**Issue by fabianhauser** [altcomphsr/altcomphsr.vshsr.ch#30]
Momentan wird der Font und die Emoticons von extern eingebunden. Falls möglich wäre es besser, dies statisch von unserer Domain zu machen.

**Comment by raphiz** [comment]
Sollte eigentlich nicht so kompliziert sein...wir brauchen einfach [alle Emojis](https://github.com/github/gemoji/tree/master/images/emoji/unicode) und müssen [etwas Kleines](https://github.com/jekyll/jemoji#customizing) in der _config.yml anpassen...
oder habe ich da was übersehen?
