### ISSUE TITLE
Dokumentationen auf Startseite durch Tipps & Tricks ersetzen

### ISSUE THREAD

**Issue by raphiz** [altcomphsr/altcomphsr.vshsr.ch#33]
Nachdem der Überlebensguide = Dokumentationen macht dieser Punkt auf der Startseite wenig Sinn.
Ich würde darum vorschlagen, dass wir diesen Punkt durch "Alternative Programme" ersetzen.

**Comment by fabianhauser** [comment]
Also ich persönlich würde eher die Tipps & Tricks auf die Startseite nehmen. Wenn jemand nach einem konkreten alternativen Programm sucht, dann findet er den Weg auch ohne einen grossen Hinweis auf der Startseite :smile: 
Wir könnten zudem noch die Community in die erste Zeile nehmen?!

**Comment by raphiz** [comment]
Passt auch! Von mir aus gerne 😄
