### ISSUE TITLE
Einführung für neue Contributer schreibern

### ISSUE THREAD

**Issue by raphiz** [altcomphsr/altcomphsr.vshsr.ch#4]
Ich habe mal die README etwas erweitert, um etwas zu erläutern, "wie was wo" dieses Repository zu gebrauchen ist und wo man mehr Informationen zu Jekyll, Docker etc bekommt.

@olidias kann man das so besser verstehen? Fehlt noch was?

**Comment by olidias** [comment]
Habs mir angesehen, schaut gut aus!:) Ich denke so sollte der Einstieg etwas einfacher fallen.. Danke!

**Comment by murieletrentini** [comment]
habe festegestellt, dass sämtliche docker commands auf dem Mac nicht funktionieren, wenn sudo benutzt wird (sehr seltsam, aber in der Community bekannt). Würde deshalb gerne das makefile wieder umändern. Wäre dann halt wieder etwas umständlich für andere, dafür für alle funktionsfähig. Einsprüche?

**Comment by raphiz** [comment]
@tarinya ja, es macht Sinn, dass Docker unter OSX nicht als root ausgeführt wird, wenn man sich überlegt wie das Setup ist.

Ich habe `sudo` wieder aus dem Make file rausgenommen und in der README ein Hinweis für OSX hinzugefügt
