### ISSUE TITLE
Netzwerkfreigaben Mac OS X

### ISSUE THREAD

**Issue by fabianhauser** [altcomphsr/altcomphsr.vshsr.ch#43]
Auf der Webseite ist der Teil der [Netzwerkfreigaben unter OS X](https://www.openhsr.ch/hsr/shares/#netzwerkfreigaben-unter-mac-os-x-einrichten) unvollständig. Wie an der Vorstandssitzung besprochen müsste der noch ergänzt oder alternativ entfernt werden.

**Comment by raphiz** [comment]
Habs rausgelöscht
