### ISSUE TITLE
Backup Software Empfehlungen

### ISSUE THREAD

**Issue by michiwieland** [altcomphsr/altcomphsr.vshsr.ch#50]
Eine Backup Software gehört meiner Meinung nach auf jeden Rechner. 

Ich denke deshalb, dass wir eine Doku zu dem Thema anbieten sollten. Sei es einerseits um die Awareness zu steigern und anderseits einen Überblick über die vorhandenen Lösungen zu geben. Welche Software nutzt ihr und würdet ihr empfehlen? Gerne würde ich hier eure Inputs sammeln und diese dann in Form einer kurzen Doku zur Verfügung stellen. 

Ich persönlich nutze Deja-Dup, welches unter Ubuntu bereits vorinstalliert ist. Dieses ist simple zu benutzen und die Backups werden per Default verschlüsselt.

**Comment by raphiz** [comment]
Eine weiter Alternative wäre [Back in Time](http://backintime.le-web.org/)
Der primäre Vorteil ist: Man kann (wohl) selektiv Dateien wiederherstellen.

**Comment by michiwieland** [comment]
Das Issue ist mit dem Pull Request bc55c1308d8429b39cbe314033447445a61b14c2 erledigt
