### ISSUE TITLE
Doku: Self-signed Zertifikat installieren

### ISSUE THREAD

**Issue by Excape** [altcomphsr/altcomphsr.vshsr.ch#53]
Eine Anleitung erstellen, wie man das HSR Root-Zertifikat installieren kann
- Die einzige "Doku" dazu unter HSR-Intern: https://www.hsr.ch/HSR-Zertifikat.14847.0.html
- Certs unter pki.hsr.ch
- Evtl. Zertifikat mit connect verteilen?
- `eduroam`-Zertifikat

**Comment by fabianhauser** [comment]
Nach diesem Issue sollte die Dokumentation unter https://www.openhsr.ch/app/thunderbird/#hsr-adressbuch repariert werden.

**Comment by raphiz** [comment]
@fabianhauser was meinst du mit dem Thunderbird Issue? Ist der AD überhaupt mit SSL/TLS erreichbar?

**Comment by fabianhauser** [comment]
@raphiz : Ja, die AD ist mit TLS erreichbar; allerdings nur mit HSR-Self-Signed Zertifikat.

**Comment by fabianhauser** [comment]
Eduroam Zertifikat: [wlan.pem.txt](https://github.com/openhsr/www.openhsr.ch/files/479581/wlan.pem.txt)

**Comment by fabianhauser** [comment]
Das Zertifikat wird in Zukunft mit dem Connect gebundled, daher kann dieses Issue geschlossen werden.
