### ISSUE TITLE
Flash unter Linux

### ISSUE THREAD

**Issue by bytinbit** [altcomphsr/altcomphsr.vshsr.ch#54]
Für einige Übungen (z.B. CN1) wird Flash benötigt, Adobe hat dessen Verwendung eingestellt. Es gibt eine Alternative - http://www.pcworld.com/article/2993902/browsers/how-to-get-the-latest-version-of-flash-on-firefox-for-linux-after-adobes-abandonment.html

Benötigt: Angabe, wie man die Alternative installiert.

**Comment by fabianhauser** [comment]
Hallo @bytinbit 

Ich würde vorschlagen, das als Tipp zu ergänzen, was meinst du?
Flash wird ja wirklich nur noch in Ausnahmefällen benötigt (und allen anderen sollten IMO langsam wirklich dazu gezwungen werden, Alternativen zu bauen...)

LG Fabian

**Comment by raphiz** [comment]
+1 als Tipp

**Comment by fabianhauser** [comment]
Ich denke, wir können dieses Issue schliessen. Flash ist inzwischen kaum mehr im Einsatz :)
