### ISSUE TITLE
Max OS X in Dokumentationen in macOS umbenennen

### ISSUE THREAD

**Issue by raphiz** [altcomphsr/altcomphsr.vshsr.ch#59]
Offenbar heisst das Ding nicht mehr `Max OS X` sondern `macOS` - wäre schön, das korrekt und einheitlich dokumentiert zu haben.
Dies ist ein einfacher Copy-Paste-Task :wink:

**Comment by michiwieland** [comment]
Die Änderungen müssen in folgenden Files vorgenommen werden:
- _hsr/vpn.md
- _layouts/index.html
- pages/community.md
- tipps/_posts/2016-10-09-dasylab.md
