### ISSUE TITLE
Startseite erstellen

### ISSUE THREAD

**Issue by fabianhauser** [altcomphsr/altcomphsr.vshsr.ch#6]
Die Startseite sollte ein kurzer und übersichtlicher Einstiegspunkt in die Webseite sein.

**Comment by fabianhauser** [comment]
Habe mal etwas Grundlegenden Inhalt zur Startseite hinzugefügt.

**TODO:** Styling (im Styl einer zweispaltige Tabelle?)
Vielleicht hat @olidias ja Lust?  :wink:

**Comment by fabianhauser** [comment]
@raphiz es scheint, als hätte ich bei 5405baae55bc76c4aa259c3e24cc285329823dbd oder 5691c1b1367dde6d3e5701cb80b7e1fac34ff112 das Deployment kaputt gemacht. Bei mir lokal funktioniert alles sauber... Könntest du das mal anschauen?

**Comment by raphiz** [comment]
@fabianhauser wenn du was am Docker-Image änderst, dass fällt der Build erstmal  auf die Schnauze..
Das ist leider so, da Dockerhub das Image neu baut und Wercker (welches das Deployment macht) auf dieses Image aufsetzt...etwas unsaubere Lösung, aber nach dem nächstem Commit (wenn Dockerhub  fertig ist) läufts auch wieder. Ich habe den Build von Hand angestupst - nun läufts auch :smile:

**Comment by fabianhauser** [comment]
Die Startseite wäre soweit bereit; allerdings fehlt noch ein catchy Slogan. Momentan steht dort _OSS, Linux, Mac und mehr_, was nicht gerade toll klingt. Hat jemand eine Idee?
