### ISSUE TITLE
Github Logo in Footer

### ISSUE THREAD

**Issue by michiwieland** [altcomphsr/altcomphsr.vshsr.ch#65]
Da wir Github als neuen Sponsor gewinnen konnten (Herzlichen Dank an @raphiz, Siehe #64), gehört natürlich auch das [Logo von Github](https://github.com/logos) in den Footer unserer Webseite. 
Ich schalge vor, wir nehmen das ausgeschriebene, da dieses ein ähnliches Format wie die übrigen Logos hat. Irgendwelche Einwände?

**Comment by fabianhauser** [comment]
Github ist kein Sponsor im Sinne von einem grösseren Beitrag, sie senden uns ein paar CheatSheets und Werbeartikel mit ihrem Logo drauf. (So habe ich das zumindest verstanden, stimmt das @raphiz?)
IMHO reicht das nicht für auf die Webseite... sonst haben wir dort bald ein Logo-Jungle :wink:

**Comment by raphiz** [comment]
Ja, ich geben @fabianhauser recht - ist nur Swag Sponsoring für den Spezifischen Event. Darum habe ich in #64 die Octocat links neben den Text des Workshops hinzugefügt. Ich denke, das sollte reichen.
Ein gigantisches Logo habe ich dafür in der README des Workshops 🙈
