### ISSUE TITLE
Dokumentationen Schreiben

### ISSUE THREAD

**Issue by fabianhauser** [altcomphsr/altcomphsr.vshsr.ch#7]
Einfach ankreuzen und evtl. einen Kommentar schreiben, wenn du eine Dokumentation erstellst!

Siehe auch [Styleguide](http://altcomp.raphael.li/styleguide/)
- [x] WLAN
  - [x] NetworkManager (Ubuntu-Netzwerk)
- [x] E-Mail-Einstellungen
  - [x] Thunderbird
- [x] VPN
  - [x] NetworkManager (Ubuntu-Netzwerk)
- [x] SMB-Shares (nur einbinden)
  - [x] Nautilus (Ubuntu-Dateimanager)
- [x] ~~Drucken~~  (#16)
- [x] ~~Alternative Software Empfehlungen~~  (#18)

~~Einfach ergänzen, falls noch was wichtiges fehlt.~~

**Comment by raphiz** [comment]
Ich frage mich, ob wir in den Dokumentationen die Installation via GUI-Tool oder Kommandozeile angeben... was meint ihr?
Oder wollen wir in den Anleitungen nur angeben "Installiere die Pakete X, Y und Z" und verlinken auf eine Installationsseite? - Ist ja auch wider je nach Gui/Distribution etc. unterschiedlich....

**Comment by fabianhauser** [comment]
Ich würde vorschlagen, in den Ubuntu-Anleitungen jeweils [APT-URLs mit einem Button zu hinterlegen (wie im ubuntuusers-Wiki)](https://wiki.ubuntuusers.de/apturl/); z.B. `apt://thunderbird`
Zudem können wir ja jeweils unter Links auf die Software-Webseite linken, dort wird ja meistens aufgezeigt, wie die Installation auf anderen Systemen funktioniert.

**Comment by raphiz** [comment]
OK, soweit so gut...aber was ist z. Bsp. mit Thunderbird unter OSX? Gibt das eine separate Seite?

**Comment by fabianhauser** [comment]
Diese könnten wir jeweils auf der gleichen Seite in einen separaten Abschnitt einfügen, falls es Unterschiede gibt. Somit wäre alles zusammen.
Allerdings hat das den Nachteil, das evtl. einzelne Seiten eher lange werden... denke das wäre aber verkraftbar.

Werde morgen sonst mal mit der Thunderbird Doku starten, es ist vermutlich am einfachsten, das Ganze™ an einem konkreten Fall auszuprobieren :smiley:

**Comment by raphiz** [comment]
Top, tönt gut! Ja wenns mal steht siehts ja nochmals anders aus...Ich mache mich morgen oder so ans VPN!

**Comment by murieletrentini** [comment]
VPN gibts bestimmt für mac mehr zu sagen als für thunderbird.  Die meisten mac user werden wohl das native mail programm verwenden.

**Comment by raphiz** [comment]
Das mit den APT-URLs war eine gute Idee, hat sich aber nicht wirklich als praktikabel erwiesen. Wenn ich einen Link auf `networkmanager-vpnc` findet das Software Center nichts...Damit ist das Ganze etwas witzlos... 
Hab's nun beim [VPN](http://altcomp.raphael.li/hsr/vpn/) via Terminal Instruktionen beschrieben, sollte auch so verständlich sein, oder?

**Comment by fabianhauser** [comment]
@raphiz Hmm, also wenn ich bei [Ubuntuusers](https://wiki.ubuntuusers.de/VPNC/#Konfiguration-ueber-die-grafische-Oberflaeche) auf den Button mit `apt://network-manager-vpnc` klicke, funktioniert es. Bist du sicher, hast du nicht nur den `-` in `network-manager` vergessen? :wink:

Aber die Kommandozeile ist auch gut verständlich. Eines unserer Ziele ist ja auch, dass die Benutzer etwas lernen. (Wobei anzuzweifeln ist, ob sie `apt-get` nach Copy-Paste besser beherrschen als auf Buttons zu klicken ^^)
Was denkst du, @olidias? `sudo apt-get install` oder lieber GUI?

**Comment by raphiz** [comment]
Aaaahwrg :persevere: :triumph:....ich Depp....ja, da ist so..habe das auch falsch Dokumentiert, werde es gleich fixen.... Trotzdem weiss ich nicht ob GUI oder Terminal...

**Comment by fabianhauser** [comment]
Haha, kann ja mal passieren :smiley: 
Ich bin nach wie vor für den Button, aber daneben noch den Paketnamen für die Poweruser hinzuschreiben.

**Comment by fabianhauser** [comment]
@olidias : Hättest du nicht Lust, die WLAN-Doku beizusteuern? :-)

**Comment by olidias** [comment]
Bezüglich GUI oder Kommandozeile, für mich scheint vpnc auf der Kommandozeile relativ einleuchtend, habe es gar nie mit dem Network-Manager benutzt. Habe dazu ein Skript auf der alten altcomp site gefunden und die Zeile mit dem Passwort rausgenommen, damit ich es nicht mit Klartext im Skript speichern muss und somit beim Ausführen gepromtet werde. Ich schaue es mir gerne an, komme aber vor Montag wahrscheinlich kaum dazu.

**Comment by raphiz** [comment]
Ich habe der liste noch "Alternative Software Empfehlungen" hinzugefügt.

Ich frage mich spezifisch bei dieser Seite wie wir das mit nicht freier Software wie bsp. MasterPDFEditor oder FoxitReader machen. Es sind Alternativen, welche auf Linux laufen, aber nicht frei sind....

**Comment by raphiz** [comment]
Hat jemand von euch die Drucker zum laufen gebracht? Ich bin bisher kläglich gescheitert 😢

**Comment by fabianhauser** [comment]
@raphiz: Ehrlich gesagt habe ich bis jetzt immer nur über mobileprint@hsr.ch mit PDF-Anhang gedruckt...
Wollen wir uns für den Anfang auf diese Möglichkeit einschränken? Evtl. erübrigt sich eine weitere Dokumentation ja, wenn jemand ein Mapper-tool entwickelt.

**Comment by raphiz** [comment]
@fabianhauser im Moment ist das sicherlich die beste Möglichkeit - bzw. Drucken via Stick geht ja auch immer 😉 
Ich würde vorschlagen wir machen ein separates Ticket auf, da schreibe ich meine bisherigen Erkenntnisse und Probleme rein - evtl. findet sich ja jemand der lust hat eine Lösung zu finden....

Ich werde Mobile-Print noch als separate Doku nachführen

-> Siehe #16

**Comment by raphiz** [comment]
Ich habe die  Alternative Software Empfehlungen in ein Separates Issue  #18 gezogen - damit können wir dieses Riesen-Ticket zumachen! 🎉
