### ISSUE TITLE
Partner-Logo

### ISSUE THREAD

**Issue by dbrgn** [altcomphsr/altcomphsr.vshsr.ch#70]
Gestern haben wir bei einer [Coredump](https://www.coredump.ch/)-Vorstandssitzung diskutiert, ob ihr eventuell Lust an einem Partner-Logo-Tausch auf der Website habt. Wir würden dann open\HSR links auf unserer Website mit Logo als "Partner" verlinken, und ihr uns auf eurer Website ebenso.

Ich denke inhaltlich würde das in beide Richtungen sehr gut passen.

Falls Interesse besteht, könnte ich auch gleich einen PR machen.

**Comment by DennisLigtenberg** [comment]
Tönt gut, Können wir gerne machen. Stellt ihr euch ein Logo im footer vor? Von mir aus können wir auch eine Kurzbeschreibung z.B. auf der Community Seite hinzufügen.

**Comment by raphiz** [comment]
Ich würde Analog zu "Unsere Sponsoren" ein Zwischentitel "unsere Partner" einfügen und drunter das Logo👍

**Comment by dbrgn** [comment]
Ihr seid verlinkt, links unter der Navi: https://www.coredump.ch/

![screenshot](https://tmp.dbrgn.ch/sponsoren.png)

Ich denke ein "unsere Partner"-Abschnitt wäre super! :) Falls ihr noch einen kurzen Text schreiben wollt auf der Community-Seite, wäre das natürlich cool.

**Comment by DennisLigtenberg** [comment]
Super so! Habt ihr ein Logo, welches wir benutzen können, oder soll ich einfach Coredump (evtl. mit der Schrift von eurer Seite, Roboto Slab) mit Link hinzufügen?

**Comment by dbrgn** [comment]
Jep, haben wir! Passt das? https://files.coredump.ch/logos/

**Comment by dbrgn** [comment]
Ping :)
