### ISSUE TITLE
Sponsor Logo Nine ersetzten

### ISSUE THREAD

**Issue by fabianhauser** [altcomphsr/altcomphsr.vshsr.ch#76]
Die Nine hat ein neues Branding und damit auch neue Logos, welche eingesetzt werden sollten:
![nine_logo claim_rgb 3](https://user-images.githubusercontent.com/368799/31661901-b34bf618-b33c-11e7-936b-ae2894e35156.png)
![nine_logo claim 2](https://user-images.githubusercontent.com/368799/31661910-b820ce5c-b33c-11e7-9acc-fb7ca08ebeb9.jpg)

**Comment by InverseIntegral** [comment]
Wurde mit #85 behoben.
