### ISSUE TITLE
Redirects funktionieren nicht mehr

### ISSUE THREAD

**Issue by InverseIntegral** [altcomphsr/altcomphsr.vshsr.ch#82]
Die beiden URLs  `/join` und `/treffpunkt` leiten nicht mehr auf die entsprechenden Seiten weiter. Dies liegt sehr wahrscheinlich an der Umstellung auf die GitHub Pages.

Mögliche Lösung für das Problem wären [JekyllRedirectFrom](https://github.com/jekyll/jekyll-redirect-from) oder [Jekyll Pageless Redirects](https://github.com/nquinlan/jekyll-pageless-redirects). Vielleicht hat sonst noch Jemand eine Idee, wie man das am besten lösen könnte.

**Comment by fabianhauser** [comment]
Siehe auch: https://help.github.com/articles/redirects-on-github-pages/

**Comment by InverseIntegral** [comment]
Wurde in #84 behoben.
