### ISSUE TITLE
NetworkManager-openconnect: Warnung vor "Save passwords"-Checkbox

### ISSUE THREAD

**Issue by das-g** [altcomphsr/altcomphsr.vshsr.ch#90]
Wir sollten die Leserin/den Leser auf https://www.openhsr.ch/hsr/vpn/ darauf hinweisen, dass sie/er die Checkbox "Save passwords" **nicht** ankreuzen sollte, um nicht (temporär?) ihren/seinen HSR-Swivel-Account gesperrt zu bekommen.

Vgl. [Issues auf NetworkManager](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues/44)- [und GNOME/NetworkManager-openconnect](https://gitlab.gnome.org/GNOME/NetworkManager-openconnect/issues/8)-GitLab

**Comment by InverseIntegral** [comment]
Habe einen Hinweis hinzugefügt (Siehe #91)

**Comment by das-g** [comment]
Erledigt durch PR #91.
