### ISSUE TITLE
VPN-Anleitung mit Zwei-Faktor-Authentisierung für MacOS erstellen

### ISSUE THREAD

**Issue by SeboCode** [altcomphsr/altcomphsr.vshsr.ch#92]
Die momentane [MacOS VPN-Anleitung](https://www.openhsr.ch/hsr/vpn/) wurde noch vor der Einführung der Zwei-Faktor-Authentisierung erstellt. Diese muss nun geupdated werden. Wir wären froh, wenn jemand mit Mac-Kenntnissen dies erledigen könnte.

**Comment by backflip** [comment]
AFAIK läuft es darauf hinaus, Cisco's AnyConnect zu installieren: https://www.cisco.com/c/en/us/support/security/anyconnect-secure-mobility-client-v4-x/model.html#~tab-downloads
Kann das jemand bestätigen?

**Comment by backflip** [comment]
Ich war mit `openconnect` erfolgreich:

1. `openconnect` installieren, hier über Homebrew:
```
brew update
brew update openconnect
```

2. Ältere OS-X-Versionen: `TunTap`-Treiber installieren: http://tuntaposx.sourceforge.net/

3. Yay
```
sudo openconnect vpn.hsr.ch
```

Quellen und weitere Infos: 
- http://kb.mit.edu/confluence/pages/viewpage.action?pageId=152588205#HowcanIconnecttotheMITVPNusingopenconnectonMacOSX%3F-Installusinghomebrewormacports
- https://gist.github.com/moklett/3170636

**Comment by fabianhauser** [comment]
Danke für die Info's @backflip! Magst du dafür vielleicht einen Pull Request aufmachen? (Für mehr Infos zu den Pull Requests, siehe die Anleitung im [README](https://github.com/openhsr/www.openhsr.ch/blob/master/README.md).)

**Comment by backflip** [comment]
@fabianhauser, here you go: https://github.com/openhsr/www.openhsr.ch/pull/105

**Comment by panmona** [comment]
Dank #105 kann man das Issue schliessen.
